/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/cat.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.69, -5.8, 1.59]}
        rotation={[Math.PI, 1.57, 0]}
        scale={-0.1}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials.Material_1}
          position={[-33.94, 133.82, -278.77]}
        />
      </group>
      <group
        position={[-0.79, -7.55, 1.57]}
        rotation={[Math.PI, 1.57, 0]}
        scale={-0.1}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials.Material_2}
          position={[-33.95, 654.34, -274.53]}
        />
      </group>
      <group
        position={[-16.72, -12.43, 26.24]}
        rotation={[Math.PI / 2, 0, 1.01]}
        scale={[-0.11, -0.1, -0.1]}
      >
        <group position={[0, 0, 68.62]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3_1.geometry}
            material={materials.Material_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3_2.geometry}
            material={materials.Material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3_3.geometry}
            material={materials.Material_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3_4.geometry}
            material={materials.Material_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3_5.geometry}
            material={materials.Material_7}
          />
        </group>
      </group>
      <group
        position={[14.93, -12.43, 26.24]}
        rotation={[-Math.PI / 2, 0, 1.01]}
        scale={[0.11, 0.1, 0.1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials.Material_5}
          position={[0, 0, 68.62]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cat.gltf");
